name: DockerExercise
on: push
jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./Source
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
         registry: ghcr.io
         username: ${ { github.actor } };
         password: ${ { secrets.PAT } }
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.7.0
      with:
        push: true
        context: ${ {env.working-directory} }/SimpleWebHalloWorld.csproj
        tags: |
          ghcr.io/MYGITUSERNAME/SimpleWebHalloWorld-1:latest
          ghcr.io/MYGITUSERNAME/SimpleWebHalloWorld-1:${ { github.run_number } }
