# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./Source
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
         registry: ghcr.io
         username: ${ { github.repository_owner } };
         password: ${ { secrets.PAT } }
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.7.0
      with:
        push: true
        context: ${ {env.working-directory} }/SimpleWebHalloWorld.csproj
        tags: |
          ghcr.io/MYGITUSERNAME/SimpleWebHalloWorld-1:latest
          ghcr.io/MYGITUSERNAME/SimpleWebHalloWorld-1:${ { github.run_number } }
